-- tfb_parking sql

ALTER TABLE `owned_vehicles`
    ADD COLUMN `stored` TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN `parking` VARCHAR(64) NULL DEFAULT NULL,
    ADD COLUMN `pound` VARCHAR(64) NULL DEFAULT NULL,
    ADD COLUMN `mileage` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `impound_reason` VARCHAR(255) NULL DEFAULT NULL,
    ADD COLUMN `impound_by` VARCHAR(128) NULL DEFAULT NULL,
    ADD COLUMN `impound_fee` INT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS `tfb_parking_impound_meta` (
    `plate` VARCHAR(16) NOT NULL,
    `reason` VARCHAR(255) NULL DEFAULT NULL,
    `impound_by` VARCHAR(128) NULL DEFAULT NULL,
    `fee` INT NOT NULL DEFAULT 0,
    `retrievable_by_owner` TINYINT(1) NOT NULL DEFAULT 1,
    `release_at` BIGINT NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`plate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
